### ISSUE TITLE
List of Drupal related software installed

### ISSUE THREAD

**Issue by theodorosploumis** [thom8/drupal8-vagrant#2]
Is there anywhere the list of the software installed? Mean software beyond git, wget and other utilities. I found out these but missing a many for sure!
- Apache
- MySQL
- Drush 8.x
- Drupal-console
- mailhog
- Solr
- Xdebug
- Xhprof
- Phpmyadmin (not set as a vhost)

Are you using the provisioner from https://github.com/geerlingguy/drupal-vm for this box?

**Comment by theodorosploumis** [comment]
Actually I was talking about the provisioner here https://github.com/thom8/acquia-vagrant/blob/master/vagrant-includes/playbook.yml.

I am Sorry.

**Comment by thom8** [comment]
@theodorosploumis it's actaully based on this project -- https://github.com/geerlingguy/acquia-cloud-vm which has recently been depreciated since functionality can be achived with Drupal VM.

However, the ansiable roles are the same as Drupal VM but this project will remain different to Drupal VM as its main function is to replicate a common Acquia environment.
